<a href="https://colab.research.google.com/github/sergeysh93/fa-hpc-practice/blob/master/mpialltoall.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install mpi4py

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 11.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for mpi4py: filename=mpi4py-3.1.6-cp310-cp310-linux_x86_64.whl size=2746317 sha256=2a401ec2cca2a3560a25a5e47fbd8c99a1faae354865b3c0f16b833e917a36d5
  Stored in directory: /root/.cache/pip/wheels/4c/ca/89/8fc1fb1c620afca13bb41c630b1f948bbf446e0aaa4b762e10
Successfully built mpi4py


In [2]:
%%writefile mpialltoall.py
from mpi4py import MPI
import numpy as np

def main():
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()

    # Создание массива случайных чисел на каждом процессе
    data = np.random.randint(0, 100, size=(size, 5))
    print(f"Процесс {rank}: Исходные данные:\n{data}\n")

    # Распределение данных между всеми процессами
    scattered_data = comm.alltoall(data)

    # Обработка данных (например, вычисление среднего значения)
    mean_values = np.mean(scattered_data, axis=1)
    print(f"Процесс {rank}: Средние значения:\n{mean_values}\n")

    # Сортировка полученных данных
    sorted_data = np.sort(scattered_data, axis=1)

    # Отправка результатов обратно всем процессам
    gathered_data = comm.alltoall(sorted_data)

    # Вывод результатов обработки
    print(f"Процесс {rank}: Полученные данные:\n{gathered_data}\n")

########## Run the main function
main()

Writing mpialltoall.py


In [3]:
! mpiexec --allow-run-as-root --oversubscribe -np 8 python "/content/mpialltoall.py"

Процесс 7: Исходные данные:
[[93 87 74 15  3]
 [ 8 69 75 10 11]
 [60 96  3 50 19]
 [97 70 97 63 91]
 [15 62 98 57 15]
 [29 53 52 25 16]
 [26 87 91 65 49]
 [88 83 52 94 96]]

Процесс 3: Исходные данные:
[[32 59 34 40 30]
 [ 6 35 58 73  5]
 [36 52 73 42 96]
 [43 71 52 62 57]
 [13 13 52 18 52]
 [52 47 98 91 93]
 [52 98  0 76  7]
 [21 94 99 25 25]]

Процесс 0: Исходные данные:
[[81 91 17 37 22]
 [98 14 38 26 37]
 [26 73 36 17  1]
 [ 6 22 11 89 31]
 [73 57 61 56 36]
 [17  5 65 55 20]
 [70 22 96 98 74]
 [18 93 88 30 19]]

Процесс 2: Исходные данные:
[[74 74 47  7 68]
 [19 67 40 82 91]
 [43  1 70 42 15]
 [49 38 79 67 67]
 [69 12 38 67 90]
 [13 81 71 98 18]
 [91 28 83 95 84]
 [76 65 17 60 44]]

Процесс 4: Исходные данные:
[[61 83 79 13 69]
 [44 85  4 40 96]
 [20 48 71 52  2]
 [51 64 26 38 86]
 [82 63 18 54 37]
 [77 55 14  1 83]
 [57 53 84 43 25]
 [32 76 43  0 38]]

Процесс 1: Исходные данные:
[[57 75 64 74  5]
 [86 41 35  4 68]
 [28 21 58 23 28]
 [ 0 47 63 52 26]
 [58  7 91 89 40]
 [29  8 56 5